# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

SETUP_DIR = 'C:\\MyProject\\Minnan\\'

a = Analysis(['MinnanCSIRDB.py',
              'BookWidget.py',
              'CreateDBConnect.py',
              'ExpertWidget.py',
              'HistoryWidget.py',
              'InstitutionWidget.py',
              'MeetThesisWidget.py',
              'PapersWidget.py',
              'PDFWidget.py',
              'PeriodicalWidget.py',
              'ThesisWidget.py',
              'C:\\MyProject\\Minnan\\RES\\img_rc.py',
              'C:\\MyProject\\Minnan\\UI\\UI_BookIndexWidget.py',
              'C:\\MyProject\\Minnan\\UI\\UI_BookInfoWidget.py',
              'C:\\MyProject\\Minnan\\UI\\UI_ExpertInfoWidget.py',
              'C:\\MyProject\\Minnan\\UI\\UI_ExpertListWidget.py',
              'C:\\MyProject\\Minnan\\UI\\UI_HistoryIndexWidget.py',
              'C:\\MyProject\\Minnan\\UI\\UI_HistoryInfoWidget.py',
              'C:\\MyProject\\Minnan\\UI\\UI_InstitutionIndexWidget.py',
              'C:\\MyProject\\Minnan\\UI\\UI_InstitutionInfoWidget.py',
              'C:\\MyProject\\Minnan\\UI\\UI_MainWidget.py',
              'C:\\MyProject\\Minnan\\UI\\UI_MainWin.py',
              'C:\\MyProject\\Minnan\\UI\\UI_MeetThesisIndexWidget.py',
              'C:\\MyProject\\Minnan\\UI\\UI_MeetThesisInfoWidget.py',
              'C:\\MyProject\\Minnan\\UI\\UI_PaperInfoWidget.py',
              'C:\\MyProject\\Minnan\\UI\\UI_PapersIndexWidget.py',
              'C:\\MyProject\\Minnan\\UI\\UI_PeriodicalIndexWidget.py',
              'C:\\MyProject\\Minnan\\UI\\UI_PeriodicalInfoWidget.py',
              'C:\\MyProject\\Minnan\\UI\\UI_ReadPDF.py',
              'C:\\MyProject\\Minnan\\UI\\UI_ThesisIndexWidget.py',
              'C:\\MyProject\\Minnan\\UI\\UI_ThesisInfoWidget.py',
              ],
             pathex=['C:\\MyProject\\Minnan'],
             binaries=[],
             datas=[(SETUP_DIR+'DB\\','DB\\')],
             hiddenimports=['sys','hashlib','os','fitz','queue','PyQt5','sqlite3','threading','tempfile','win32api','win32print'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='闽南文化研究信息资源数据库',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=False )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='闽南文化研究信息资源数据库')
